version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.21.1-browsers
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm i -f
            fi
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test Project
          command: npm run test-lib-ci
      - run:
          name: Install sonar scanner
          command: 'sudo npm install -i -g sonarqube-scanner'
      - run:
          name: Run Sonar scanner
          command: sonar-scanner
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          context: SonarCloud